"""
Multi-Agent Prompt Templates (Exp3) - Survey-Based Design

Key Design: TP/CP/SP/PA/SC constructs come from SURVEY DATA (INPUT),
not generated by LLM (OUTPUT). LLM makes decisions based on given profile.

Agents:
- Household Agent: Decision based on psychological profile
- Insurance Agent: Premium decisions based on market data
- Government Agent: Policy decisions based on adoption metrics
"""

from typing import Dict, Any, List

# =============================================================================
# CONSTRUCT DESCRIPTIONS (for prompt verbalization)
# =============================================================================

TP_DESCRIPTIONS = {
    "LOW": "You feel relatively safe from flood threats",
    "MODERATE": "You recognize some flood risk but it's manageable",
    "HIGH": "You feel seriously threatened by potential flooding"
}

CP_DESCRIPTIONS = {
    "LOW": "You doubt your ability to afford protective measures",
    "MODERATE": "You believe you could manage some protective actions with effort",
    "HIGH": "You are confident you can afford and implement protections"
}

SP_DESCRIPTIONS = {
    "LOW": "You don't expect much help from government programs",
    "MODERATE": "You believe some government support is available",
    "HIGH": "You trust the government will provide substantial assistance"
}

PA_DESCRIPTIONS = {
    "NONE": "You have not taken any protective measures yet",
    "PARTIAL": "You have some protection (insurance OR elevation)",
    "FULL": "You have comprehensive protection (insurance AND elevation)"
}

SC_DESCRIPTIONS = {
    "LOW": "You lack confidence in taking effective action",
    "MODERATE": "You have some confidence but uncertainty remains",
    "HIGH": "You are confident you can successfully protect your home"
}

# =============================================================================
# HOUSEHOLD AGENT PROMPT (Survey-Based)
# =============================================================================

HOUSEHOLD_PROMPT = """You are a {tenure_type} in a flood-prone city{mg_context}.

=== YOUR PSYCHOLOGICAL PROFILE ===
Based on your experiences and beliefs:
- Threat Perception (TP): {tp_level} - {tp_desc}
- Coping Perception (CP): {cp_level} - {cp_desc}
- Subsidy Perception (SP): {sp_level} - {sp_desc}
- Prior Adaptation (PA): {pa_level} - {pa_desc}
- Self-Confidence (SC): {sc_level} - {sc_desc}

=== YOUR CURRENT SITUATION ===
{elevation_status}
{insurance_status}
{damage_history}

=== YOUR MEMORY ===
{memory}

=== THIS YEAR'S CONDITIONS ===
Year: {year}
{flood_status}
Government subsidy: {subsidy_rate:.0%} of elevation cost
Insurance premium: {premium_rate:.1%} of property value

=== YOUR TASK ===
Given your psychological profile and current situation, choose ONE action:
{options}

Think about how your TP, CP, SP, PA, and SC influence this decision.

=== OUTPUT FORMAT ===
Respond using EXACTLY this format (no markdown):

Reasoning: [2-3 sentences explaining how your profile (TP/CP/SP/PA/SC) led to this decision]
Final Decision: [Number only: {valid_choices}]
"""

# Options based on agent type
OPTIONS_OWNER_NON_ELEVATED = """1. Buy flood insurance (Annual cost, financial protection)
2. Elevate your house (High cost, subsidy available, prevents damage)
3. Relocate (Leave neighborhood permanently)
4. Do nothing (No cost, remain exposed)"""

OPTIONS_OWNER_ELEVATED = """1. Buy flood insurance (Additional financial protection)
2. Relocate (Leave neighborhood permanently)
3. Do nothing (Your house has elevation protection)"""

OPTIONS_RENTER = """1. Buy renter's flood insurance (Protect belongings)
2. Relocate (Move to safer area)
3. Do nothing (No cost, belongings at risk)"""

# Context templates
MG_CONTEXT = {
    True: ", with limited financial resources",
    False: ""
}

TENURE_TYPE = {
    "Owner": "homeowner",
    "Renter": "renter"
}


def build_household_prompt(
    agent_state: Dict[str, Any],
    constructs: Dict[str, str],  # TP, CP, SP, PA, SC levels from survey
    context: Dict[str, Any],
    memory: List[str]
) -> str:
    """
    Build prompt for Household Agent.
    
    Args:
        agent_state: Agent's current state (elevated, has_insurance, etc.)
        constructs: Survey-derived construct levels {"TP": "HIGH", "CP": "MODERATE", ...}
        context: Year's context (subsidy_rate, premium_rate, flood_occurred)
        memory: Retrieved memories from CognitiveMemory
    """
    
    # Demographics
    mg = agent_state.get("mg", False)
    tenure = agent_state.get("tenure", "Owner")
    elevated = agent_state.get("elevated", False)
    has_insurance = agent_state.get("has_insurance", False)
    cumulative_damage = agent_state.get("cumulative_damage", 0)
    property_value = agent_state.get("property_value", 300000)
    
    # Context
    subsidy_rate = context.get("government_subsidy_rate", 0.5)
    premium_rate = context.get("insurance_premium_rate", 0.05)
    flood_occurred = context.get("flood_occurred", False)
    year = context.get("year", 1)
    
    # Construct descriptions
    tp_level = constructs.get("TP", "MODERATE")
    cp_level = constructs.get("CP", "MODERATE")
    sp_level = constructs.get("SP", "MODERATE")
    pa_level = constructs.get("PA", "NONE")
    sc_level = constructs.get("SC", "MODERATE")
    
    tp_desc = TP_DESCRIPTIONS.get(tp_level, "")
    cp_desc = CP_DESCRIPTIONS.get(cp_level, "")
    sp_desc = SP_DESCRIPTIONS.get(sp_level, "")
    pa_desc = PA_DESCRIPTIONS.get(pa_level, "")
    sc_desc = SC_DESCRIPTIONS.get(sc_level, "")
    
    # Build components
    mg_context = MG_CONTEXT[mg]
    tenure_type = TENURE_TYPE[tenure]
    
    elevation_status = "Your house is ELEVATED (protected)." if elevated else "Your house is NOT elevated."
    insurance_status = "You HAVE flood insurance." if has_insurance else "You do NOT have flood insurance."
    
    if cumulative_damage > 0:
        damage_pct = cumulative_damage / property_value * 100 if property_value > 0 else 0
        damage_history = f"Past flood damage: ${cumulative_damage:,.0f} ({damage_pct:.1f}% of property)"
    else:
        damage_history = "No significant past flood damage."
    
    # Memory
    if memory:
        memory_text = "\n".join(f"- {m}" for m in memory[-5:])
    else:
        memory_text = "- No significant events recalled."
    
    # Flood status
    flood_status = "⚠️ A FLOOD occurred this year!" if flood_occurred else "No flood this year."
    
    # Options
    if tenure == "Renter":
        options = OPTIONS_RENTER
        valid_choices = "1, 2, or 3"
    elif elevated:
        options = OPTIONS_OWNER_ELEVATED
        valid_choices = "1, 2, or 3"
    else:
        options = OPTIONS_OWNER_NON_ELEVATED
        valid_choices = "1, 2, 3, or 4"
    
    return HOUSEHOLD_PROMPT.format(
        tenure_type=tenure_type,
        mg_context=mg_context,
        tp_level=tp_level, tp_desc=tp_desc,
        cp_level=cp_level, cp_desc=cp_desc,
        sp_level=sp_level, sp_desc=sp_desc,
        pa_level=pa_level, pa_desc=pa_desc,
        sc_level=sc_level, sc_desc=sc_desc,
        elevation_status=elevation_status,
        insurance_status=insurance_status,
        damage_history=damage_history,
        memory=memory_text,
        year=year,
        flood_status=flood_status,
        subsidy_rate=subsidy_rate,
        premium_rate=premium_rate,
        options=options,
        valid_choices=valid_choices
    )


# =============================================================================
# INSURANCE AGENT PROMPT
# =============================================================================

INSURANCE_PROMPT = """You are the risk management AI for an insurance company.

=== CURRENT METRICS ===
- Loss Ratio: {loss_ratio:.1%} (Claims / Premiums)
- Active Policies: {total_policies}
- Risk Pool: ${risk_pool:,.0f}
- Current Premium Rate: {premium_rate:.2%}

=== RECENT HISTORY ===
{history}

=== TASK ===
Decide on premium adjustment for next year.

Options:
1. RAISE premium (improve solvency, may reduce uptake)
2. LOWER premium (attract customers, increase exposure)
3. MAINTAIN current premium

=== OUTPUT FORMAT ===
Analysis: [One sentence about risk situation]
Decision: [RAISE/LOWER/MAINTAIN]
Adjustment: [Percentage, e.g., 5%]
Reason: [Brief explanation]
"""

def build_insurance_prompt(state: Dict[str, Any], history: List[str]) -> str:
    """Build prompt for Insurance Agent."""
    history_text = "\n".join(f"- {h}" for h in history[-3:]) if history else "- No recent history."
    
    return INSURANCE_PROMPT.format(
        loss_ratio=state.get("loss_ratio", 0),
        total_policies=state.get("total_policies", 0),
        risk_pool=state.get("risk_pool", 1000000),
        premium_rate=state.get("premium_rate", 0.05),
        history=history_text
    )


# =============================================================================
# GOVERNMENT AGENT PROMPT
# =============================================================================

GOVERNMENT_PROMPT = """You are a government policy advisor for flood mitigation.

=== BUDGET STATUS ===
- Annual Budget: ${annual_budget:,.0f}
- Remaining: ${budget_remaining:,.0f}
- Current Subsidy Rate: {subsidy_rate:.0%}

=== ADOPTION METRICS ===
- MG (Marginalized) Adoption: {mg_adoption:.1%}
- NMG Adoption: {nmg_adoption:.1%}

=== RECENT EVENTS ===
{events}

=== TASK ===
Decide subsidy policy for next year.

Options:
1. INCREASE subsidy (faster adoption, faster budget use)
2. DECREASE subsidy (conserve budget, slower adoption)
3. MAINTAIN current rate

=== OUTPUT FORMAT ===
Analysis: [One sentence about adoption situation]
Decision: [INCREASE/DECREASE/MAINTAIN]
Adjustment: [Percentage, e.g., 10%]
Priority: [MG/ALL]
Reason: [Brief explanation]
"""

def build_government_prompt(state: Dict[str, Any], events: List[str]) -> str:
    """Build prompt for Government Agent."""
    events_text = "\n".join(f"- {e}" for e in events[-3:]) if events else "- No major events."
    
    return GOVERNMENT_PROMPT.format(
        annual_budget=state.get("annual_budget", 500000),
        budget_remaining=state.get("budget_remaining", 500000),
        subsidy_rate=state.get("subsidy_rate", 0.5),
        mg_adoption=state.get("mg_adoption_rate", 0),
        nmg_adoption=state.get("nmg_adoption_rate", 0),
        events=events_text
    )
