
import pandas as pd
from pathlib import Path

# Path to the excel file generated by master_synthesis.py
excel_path = "examples/single_agent/analysis/sq1_metrics_rules.xlsx"

if Path(excel_path).exists():
    df = pd.read_excel(excel_path)
    # Select and rename columns as requested by user
    # User asked for: Panic_Freq_% Panic_Count Elevate_Freq_% Elevate_Count Complacency_% Complacency_Count Intervention
    
    # Check if columns exist (based on my update to master_synthesis.py)
    # The columns I added were: Panic_Freq_%, Panic_Count, Elevate_Freq_%, Elevate_Count, Complacency_%, Complacency_Count
    
    cols = ['Model', 'Group', 'N_Sim', 'Panic_Freq_%', 'Panic_Count', 'Elevate_Freq_%', 'Elevate_Count', 'Complacency_%', 'Complacency_Count', 'Intv']
    
    valid_cols = [c for c in cols if c in df.columns]
    
    
    # Print header
    header = f"{'Model':<18} {'Group':<8} {'Panic%':<8} {'Panic#':<8} {'Leaks#':<8} {'Elev%':<8} {'Elev#':<8} {'Comp%':<8} {'Comp#':<8} {'Intv'}"
    print(header)
    print("-" * len(header))
    
    for idx, row in df[valid_cols + ['V1_Act']].iterrows():
        print(f"{row['Model']:<18} {row['Group']:<8} {row['Panic_Freq_%']:<8} {row['Panic_Count']:<8} {row['V1_Act']:<8} {row['Elevate_Freq_%']:<8} {row['Elevate_Count']:<8} {row['Complacency_%']:<8} {row['Complacency_Count']:<8} {row['Intv']}")

else:
    print(f"File not found: {excel_path}")
