"""Generate a minimal test fixture domain package (Phase 6R-A).

Test-time counterpart to ``broker.tools.scaffold_domain``. The full
``scaffold_domain`` produces a paper-grade WAGF domain skeleton (10+
files, ~600 LOC of boilerplate). ``gen_test_fixture`` produces the
SMALLEST possible domain package: just ``__init__.py`` +
``pack.py`` (~30 LOC total) sufficient to register a ``DomainPack``
in tests without inline ``class FakePack(DefaultDomainPack)``
boilerplate scattered across test files.

The output mirrors the ``examples/_test_fixtures/fake_traffic/``
shape (Phase 6Q-F-2-a) but stripped of YAML configs, mock LLM
responses, and prompt templates — those are only needed for end-to-end
``ExperimentRunner.run`` exercises (which the existing fake_traffic
fixture provides). Test fixtures generated here are sufficient for
**hook-level unit tests**: register a pack, override one method, assert
the broker's consumer subsystem queries it correctly.

Usage::

    python -m broker.tools.gen_test_fixture \\
        --domain test_reflection_x \\
        --output examples/_test_fixtures/

After generation, the test imports the package + customises:

.. code-block:: python

    import examples._test_fixtures.test_reflection_x  # registers pack
    from examples._test_fixtures.test_reflection_x.pack import (
        TestReflectionXDomainPack,
    )

    class MyCustomPack(TestReflectionXDomainPack):
        def reflection_status_text(self, context):
            return "custom narrative"

The ``--sub-pack`` flag is informational today (records the intended
sub-protocol focus in the generated pack's docstring); it becomes
load-bearing after Phase 6R-D wires the sub-protocol split, when
``gen_test_fixture --sub-pack reflection`` will emit a minimal
``ReflectionPack``-implementing class instead of inheriting all 31
methods from ``DefaultDomainPack``.

Reference:
- ``examples/_test_fixtures/fake_traffic/`` — full fixture-package
  reference (Phase 6Q-F-2-a/b/c).
- ``broker.tools.scaffold_domain`` — production-grade scaffolder.

Phase 6R-A (2026-05-26). See
``~/.claude/plans/swirling-knitting-lighthouse.md``.
"""
from __future__ import annotations

import argparse
import keyword
import sys
from pathlib import Path
from textwrap import dedent
from typing import Optional


# ---------------------------------------------------------------------------
# Template generators
# ---------------------------------------------------------------------------

_VALID_SUB_PACKS = frozenset({
    "reflection", "memory", "skill", "event",
    "perception", "governance", "setup", "any",
})


def _class_name(domain: str) -> str:
    """Convert ``test_reflection_x`` → ``TestReflectionXDomainPack``."""
    return "".join(part.capitalize() for part in domain.split("_")) + "DomainPack"


def gen_package_init(domain: str, sub_pack: str) -> str:
    """Top-level ``__init__.py`` — registers DomainPack at import time."""
    class_name = _class_name(domain)
    return dedent(f'''\
        """Minimal test fixture domain package — ``{domain}``.

        Generated by ``broker.tools.gen_test_fixture`` (Phase 6R-A).
        NOT for paper-shipping use. Exists so tests can register a
        DomainPack via ``import examples._test_fixtures.{domain}``
        without inlining ``class FakePack(DefaultDomainPack)``
        boilerplate.

        Intended sub-protocol focus: ``{sub_pack}``. Today (pre-Phase
        6R-D) all DomainPack methods inherit from DefaultDomainPack;
        after the sub-protocol split this fixture will narrow to only
        the ``{sub_pack}`` sub-protocol surface.
        """
        try:
            from broker.domains.registry import DomainPackRegistry
            from .pack import {class_name}
            DomainPackRegistry.register("{domain}", {class_name}())
        except ImportError:
            # Broker not importable at fixture-load time (partial bring-up).
            # Mirrors examples.governed_flood / .vaccination_demo silent-skip.
            # Relative import (vs absolute ``examples._test_fixtures.X``) so the
            # generated fixture works from any output directory — including
            # pytest tmp_path-rooted scratch trees.
            pass
        ''')


def gen_pack(domain: str, sub_pack: str) -> str:
    """``pack.py`` — minimal ``DefaultDomainPack`` subclass."""
    class_name = _class_name(domain)
    return dedent(f'''\
        """{class_name} — minimal test fixture DomainPack.

        Generated by ``broker.tools.gen_test_fixture`` (Phase 6R-A).
        Inherits every default behaviour from ``DefaultDomainPack``;
        tests override individual hooks via subclassing.

        Intended sub-protocol focus: ``{sub_pack}``.

        Typical use in a test::

            import examples._test_fixtures.{domain}  # registers pack
            from examples._test_fixtures.{domain}.pack import {class_name}

            class _MyOverride({class_name}):
                def reflection_status_text(self, context):
                    return "custom narrative for this test"

            # Re-register the override for the duration of this test.
            DomainPackRegistry.register("{domain}", _MyOverride())
            ...
        """
        from broker.domains.default import DefaultDomainPack


        class {class_name}(DefaultDomainPack):
            """Test fixture pack — no behaviour overrides by default."""
            name: str = "{domain}"
        ''')


# ---------------------------------------------------------------------------
# I/O orchestration
# ---------------------------------------------------------------------------

def write_fixture(
    domain: str,
    output_dir: Path,
    sub_pack: str = "any",
    overwrite: bool = False,
) -> Path:
    """Write the 2-file fixture package. Returns the package directory.

    Raises ``FileExistsError`` if the package directory already exists
    and ``overwrite=False``.
    """
    if not domain.isidentifier():
        raise ValueError(
            f"--domain '{domain}' must be a valid Python identifier "
            "(letters, digits, underscores; cannot start with digit)."
        )
    # `str.isidentifier()` returns True for Python keywords (`class`,
    # `def`, `import`, ...) — those pass the syntax check but blow up
    # at import time with SyntaxError when the package is loaded. Catch
    # them explicitly. Per Phase 6R-A reviewer must-fix #1.
    if keyword.iskeyword(domain):
        raise ValueError(
            f"--domain '{domain}' must not be a Python keyword "
            f"(e.g. 'class', 'def', 'import'). Pick a different name."
        )
    if sub_pack not in _VALID_SUB_PACKS:
        raise ValueError(
            f"--sub-pack '{sub_pack}' must be one of {sorted(_VALID_SUB_PACKS)}."
        )

    pkg_dir = output_dir / domain
    if pkg_dir.exists() and not overwrite:
        raise FileExistsError(
            f"fixture directory {pkg_dir} already exists. "
            "Pass --overwrite to replace, or pick a different --domain name."
        )
    pkg_dir.mkdir(parents=True, exist_ok=True)

    (pkg_dir / "__init__.py").write_text(
        gen_package_init(domain, sub_pack),
        encoding="utf-8",
    )
    (pkg_dir / "pack.py").write_text(
        gen_pack(domain, sub_pack),
        encoding="utf-8",
    )
    return pkg_dir


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m broker.tools.gen_test_fixture",
        description=(
            "Generate a minimal test fixture DomainPack package. "
            "Sister tool to broker.tools.scaffold_domain (production-grade)."
        ),
    )
    parser.add_argument(
        "--domain",
        required=True,
        help=(
            "Python identifier for the domain name (e.g. 'test_reflection_x'). "
            "Becomes the package directory name + the DomainPack `name` field."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("examples/_test_fixtures"),
        help=(
            "Parent directory for the fixture package "
            "(default: examples/_test_fixtures)."
        ),
    )
    parser.add_argument(
        "--sub-pack",
        choices=sorted(_VALID_SUB_PACKS),
        default="any",
        help=(
            "Informational tag declaring which sub-protocol this fixture is "
            "intended to exercise. **No effect on generated code today** — "
            "the flag's value is recorded in the generated pack's docstring "
            "only. Becomes structurally load-bearing after Phase 6R-D wires "
            "the sub-protocol split (default: any)."
        ),
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace an existing fixture directory of the same name.",
    )
    return parser


def main(argv: Optional[list] = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        pkg_dir = write_fixture(
            domain=args.domain,
            output_dir=args.output,
            sub_pack=args.sub_pack,
            overwrite=args.overwrite,
        )
    except (ValueError, FileExistsError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    print(f"Generated test fixture at: {pkg_dir}")
    print("Next steps:")
    print(f"  1. Add `import examples._test_fixtures.{args.domain}` "
          f"to your test module top.")
    print(f"  2. Subclass `{_class_name(args.domain)}` to override hooks.")
    print(f"  3. Re-register the subclass for the test's duration.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
